# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:



# Define a job to be invoked later in a workflow.
jobs:
  create_infrastructure:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    docker:
      - image: amazon/aws-cli
    # Add steps to the job. Steps to create a cloudformation stack
    steps:
      - checkout
      - run:
          name: "Create Cloudformation Stack"
          command: |
            aws cloudformation deploy \
            --template-file cf-template.yml \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --region us-east-1

# Invoke jobs via workflows
workflows:
  my_infrastructure:
    jobs:
      - create_infrastructure
